// <auto-generated />
using API_CRUD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_CRUD.Migrations
{
    [DbContext(typeof(PlayerContext))]
    [Migration("20210705050039_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_CRUD.Models.Player", b =>
                {
                    b.Property<int>("P_Jno")
                        .HasColumnType("int");

                    b.Property<int>("P_Age")
                        .HasColumnType("int");

                    b.Property<string>("P_Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("P_Jno");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
